vote_urls: [
  "https://minecraft-mp.com/server/208937/vote/",
  "https://servers-minecraft.com/vote/2693",
  "https://topminecraftservers.org/vote/16936",
  "https://minecraft.buzz/vote/4132",
]
email_sender: "kylebrooks.garzon@gmail.com"
email_password: "zpcm naeu mann iwra"
email_reciever: "kylebrooks.garzon@gmail.com"
minecraft_username: "The_Game12"
os_type: "macOS"
browser: 'Google\ Chrome'